# Generated by Django 2.1.7 on 2019-03-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chan_dashboard', '0005_auto_20190326_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='price_1',
            new_name='price_staff',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='price_2',
            new_name='price_student',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='price_3',
            new_name='price_vip',
        ),
        migrations.AddField(
            model_name='bookdate',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('completed', 'Completed'), ('cancel', 'Cancel')], default='waiting', max_length=10),
        ),
    ]
