# Generated by Django 2.1.7 on 2019-03-26 08:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['orderDate'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('price_normal', models.DecimalField(decimal_places=0, max_digits=10)),
                ('price_1', models.DecimalField(decimal_places=0, max_digits=10)),
                ('price_2', models.DecimalField(decimal_places=0, max_digits=10)),
                ('price_3', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['typename'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, upload_to='users/%y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('phone', models.IntegerField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('job', models.CharField(choices=[('STUDENT', 'Student'), ('STAFF', 'Staff'), ('VIP', 'Vip')], default='student', max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('note', models.TextField(blank=True)),
                ('facebook', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chan_dashboard.User'),
        ),
        migrations.AddField(
            model_name='bookdate',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chan_dashboard.Category'),
        ),
        migrations.AddField(
            model_name='bookdate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chan_dashboard.User'),
        ),
    ]
