# Generated by Django 2.1.7 on 2019-03-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chan_dashboard', '0004_auto_20190326_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('STAFF', 'Staff'), ('VIP', 'Vip')], default='student', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
    ]
