"""
Django settings for chanhouse_base project.

Generated by 'django-admin startproject' using Django 2.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
from pathlib import Path

# Utilities
PROJECT_PACKAGE = Path(__file__).resolve().parent

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'h_^+h+@u!6hl5zitywaejy(sly5-2s%rl9k$ym&0+fkc&xw)9m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


def getHost():
    filePath = os.path.dirname(os.path.abspath(__file__)) + "/../myhost.txt"
    getHost = open(filePath).read().split("\n")
    getHost = [x for x in getHost if x]  # delete empty elements
    return getHost


ALLOWED_HOSTS = getHost()

# Application definition

INSTALLED_APPS = [
    'administrator.apps.AdministratorConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'import_export',
    'chanhouse_base.chan_dashboard.apps.ChanDashboardConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    'DATETIME_FORMAT': "%d/%m/%Y %H:%M",
}

ROOT_URLCONF = 'chanhouse_base.urls'

IMPORT_EXPORT_USE_TRANSACTIONS = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
<<<<<<< HEAD
        'DIRS': [str(PROJECT_PACKAGE.joinpath('templates'))],
=======
        'DIRS': [
            os.path.join(BASE_DIR, 'chanhouse_base', 'templates'),
        ],
>>>>>>> 8672578dbb142c8120fea3595bd9bafd116358e3
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chanhouse_base.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'chanhouse_db',
        'USER': 'chanhouse_db_user',
        'PASSWORD': 'chanhouse_db_password',
        'HOST': 'localhost',
        'PORT': '',
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

<<<<<<< HEAD
STATICFILES_DIRS = [str(PROJECT_PACKAGE.joinpath('static'))]
STATIC_URL = '/static/'
=======
STATIC_URL = '/chanhouse_base/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'chanhouse_base/static'),
)
>>>>>>> 8672578dbb142c8120fea3595bd9bafd116358e3
